import matplotlib.pyplot as plt

def make_figure(points):
    """
    Get the points generated by evaluate_function() and return
    a matplotlib figure object.
    You can display the plot by calling .show() on it.

    >>> make_figure(((1, 2), (2, 3), (3, 4))).show() # doctest: +SKIP
    """
    # ((1, 2), (3, 4), (5, 6))  ->  ((1, 3, 5), (2, 4, 6))
    xs, ys = tuple(zip(*points))

    x_range = (min(xs), max(xs))
    y_range = (min(ys), max(ys))

    figure, axes = plt.subplots()
    axes.plot(xs, ys)
    axes.axis([*x_range, *y_range])
    return figure
